# Generated by Django 5.1.3 on 2026-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
