# Generated by Django 5.1.3 on 2026-03-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_alter_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
