# Generated by Django 5.1.3 on 2026-03-01 18:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0002_alter_meter_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_rwf', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Card'), ('cash', 'Cash')], default='momo', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='meters.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_generated', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('token_generated', models.CharField(max_length=25, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='created', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_purchases', to='meters.meter')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='token_purchase', to='transactions.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_2cf806_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['meter'], name='transaction_meter_i_78b76b_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenpurchase',
            index=models.Index(fields=['meter'], name='transaction_meter_i_4f5193_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenpurchase',
            index=models.Index(fields=['status'], name='transaction_status_e4b09b_idx'),
        ),
    ]
